export const PULSE_SHOW_VIEW_MODAL = 'PULSE_SHOW_VIEW_MODAL';
export const PULSE_HIDE_VIEW_MODAL = 'PULSE_HIDE_VIEW_MODAL';
export const PULSE_SHOW_CREAT_MODAL = 'PULSE_SHOW_CREAT_MODAL';
export const PULSE_HIDE_CREAT_MODAL = 'PULSE_HIDE_CREAT_MODAL';
